# Generated by Django 2.0.7 on 2019-05-30 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminEmpresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tipoUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descUsuario', models.CharField(blank=True, max_length=70, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='admindatos',
            name='id_tipoUsuario',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='adminEmpresa.tipoUsuario'),
            preserve_default=False,
        ),
    ]
