# Generated by Django 2.0.7 on 2019-05-30 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminEmpresa', '0002_auto_20190530_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admindatos',
            name='id_tipoUsuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminEmpresa.tipoUsuario'),
        ),
        migrations.AlterField(
            model_name='tipousuario',
            name='descUsuario',
            field=models.CharField(blank=True, default=0, max_length=70),
            preserve_default=False,
        ),
    ]
