# Generated by Django 2.0.7 on 2019-05-30 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='localDatos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion_local', models.CharField(blank=True, max_length=70, null=True)),
                ('rutEmpresa', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='empresa.empresaDatos')),
            ],
        ),
    ]
