# Generated by Django 2.0.7 on 2019-06-04 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='localdatos',
            name='nro_local',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
