# Generated by Django 2.0.7 on 2019-06-07 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locales', '0002_localdatos_nro_local'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localdatos',
            name='nro_local',
        ),
    ]
