# Generated by Django 2.0.7 on 2019-05-23 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='productos',
            new_name='Productos1',
        ),
    ]
