# Generated by Django 2.0.7 on 2019-05-23 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_auto_20190523_1345'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Productos1',
            new_name='Productos',
        ),
    ]
