# Generated by Django 2.0.7 on 2019-06-06 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_auto_20190603_1310'),
        ('productos', '0005_auto_20190603_1310'),
    ]

    operations = [
        migrations.CreateModel(
            name='productosLocal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreProducto', models.CharField(max_length=70)),
                ('direccion_local', models.CharField(max_length=70)),
                ('rutEmpresa', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='empresa.empresaDatos')),
            ],
        ),
        migrations.AlterField(
            model_name='productos',
            name='precio',
            field=models.IntegerField(),
        ),
    ]
